{
  pkgs,
  config,
  lib,
  ...
}:

let
  border-size = config.var.theme.border-size;
  gaps-in = config.var.theme.gaps-in;
  gaps-out = config.var.theme.gaps-out;
  active-opacity = config.var.theme.active-opacity;
  inactive-opacity = config.var.theme.inactive-opacity;
  rounding = config.var.theme.rounding;
  blur = config.var.theme.blur;
  keyboardLayout = config.var.keyboardLayout;
in
{
  imports = [
    ./animations.nix
    ./bindings.nix
    # ./hyprspace.nix
    ./hypridle.nix
    ./hyprpaper.nix
    # ./waybar.nix
    # ./../waybar/default.nix
    ./hyprlock.nix
    ./hyprdynamicmonitors.nix
    # ./hyprpanel.nix
  ];
  # programs.hyprpanel.enable = true;

  home.packages = with pkgs; [
    # qt5.qtwayland
    # qt6.qtwayland
    # libsForQt5.qt5ct
    # qt6ct
    hyprshot
    hyprpicker
    swappy
    imv
    wf-recorder
    wlr-randr
    wl-clipboard
    brightnessctl
    gnome-themes-extra
    libva
    dconf
    wayland-utils
    wayland-protocols
    glib
    direnv
    meson
  ];

  wayland.windowManager.hyprland = {
    enable = true;
    xwayland.enable = true;
    # systemd.enable = true;
    #
    extraConfig = ''
      exec-once = hyprpanel;
      exec-once = kdeconnect-indicator;
      exec-once = "thunderbird --headless";
      # source = ${config.home.homeDirectory}/.config/hypr/config.d/99_autogenerated-monitors.conf;

      env = XDG_SESSION_TYPE,wayland


      env = __GLX_VENDOR_LIBRARY_NAME,nvidia

      env = WLR_NO_HARDWARE_CURSORS,1


                              #       windowrule = opacity 0.0 override, class:^(xwaylandvideobridge)$
                              # windowrule = noanim, class:^(xwaylandvideobridge)$
                              # windowrule = noinitialfocus, class:^(xwaylandvideobridge)$
                              # windowrule = maxsize 1 1, class:^(xwaylandvideobridge)$
                              # windowrule = noblur, class:^(xwaylandvideobridge)$
                              # windowrule = nofocus, class:^(xwaylandvideobridge)$

                        #       windowrule {
                        #     name = hyde_picture_in_picture
                        #     match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
                        #     tag = +picture-in-picture
                        #     tag = +hyde_picture_in_picture
                        #     float = true
                        #     keep_aspect_ratio = true
                        #     move = (monitor_w*0.73) (monitor_h*0.72)
                        #     size = (monitor_w*0.25) (monitor_h*0.25)
                        #     pin = true
                        # }

            # windowrule = match:class float, title:^(Picture in picture)$
            # windowrule = match:pin, title:^(Picture in picture)$
    '';

    settings = {

      "$mod" = "SUPER";
      "$shiftMod" = "SUPER_SHIFT";
      "$ctrlMod" = "SUPER_CTRL";

      monitor = [
        "eDP-1,2560x1600@165.0,0x1080,1.6"
        "eDP-2,2560x1600@165.0,0x1080,1.6"
        "desc:Sceptre Tech Inc Sceptre F24 0x00000001,1920x1080@75.0,1920x0,1.0"
        "HDMI-A-1,1920x1080@75,0x0,1.0"

        ",prefered,auto,1"
      ];

      cursor = {
        # no_hardware_cursors = true;
        default_monitor = "eDP-2";
      };

      general = {
        resize_on_border = true;
        gaps_in = gaps-in;
        gaps_out = gaps-out;
        border_size = border-size;
        # border_part_of_window = true;
        layout = "master";
      };

      decoration = {
        active_opacity = active-opacity;
        inactive_opacity = inactive-opacity;
        rounding = rounding;
        shadow = {
          enabled = true;
          range = 20;
          render_power = 3;
          color = lib.mkForce "rgba(00000055)";
        };
        blur = {
          enabled = if blur then "true" else "false";
          size = 3;
          passes = 1;
          new_optimizations = true;
          ignore_opacity = false;
        };
      };

      master = {
        new_status = true;
        allow_small_split = true;
        mfact = 0.5;
      };

      # gestures = {
      #   workspace_swipe = true;
      # };

      blurls = [
        "gtk-layer-shell"
        "notifications"
        "wofi"
        "rofi"
        "power-menu"
        "anyrun"
      ];

      # layerrule = [
      #   "blur, gtk-layer-shell"
      #   "blur, notifications"
      #   "blur, wofi"
      #   "blur, rofi"
      #   "blur, anyrun"
      # ];

      # windowrule = [
      #   "opacity 0.95, .*"
      # ];

      misc = {
        # vfr = true;
        disable_hyprland_logo = true;
        disable_splash_rendering = true;
        disable_autoreload = false;
        focus_on_activate = true;
        animate_mouse_windowdragging = true;
        enable_swallow = true;
        # new_window_takes_over_fullscreen = 2;
      };

    };
  };

}
