{ pkgs, lib, ... }:
{
  home.packages = [ pkgs.hyprdynamicmonitors ];

  # home.file = {
  #   ".config/hypr/config.d/99_autogenerated-monitors.conf".text = ''
  #     # Populated by hyprdynamicmonitors
  #   '';
  # };

  home.hyprdynamicmonitors = {
    enable = true;
    # config = ''
    #   [general]
    #   destination = "$HOME/.config/hypr/config.d/99_autogenerated-monitors.conf"
    #   debounce_time_ms = 1500
    #
    #   [profiles.sceptre]
    #   config_file = "hyprconfigs/sceptre.conf"
    #   config_file_type = "static"
    #
    #   [[profiles.sceptre.conditions.required_monitors]]
    #   description = "Sceptre Tech Inc Sceptre F24"
    #
    #   [fallback_profile]
    #   config_file = "hyprconfigs/laptop.conf"
    #   config_file_type = "static"
    # '';
    # extraFiles = {
    #   "hyprdynamicmonitors/hyprconfigs" = ./hyprconfigs;
    # };
  };
}
